trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
  - script: pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: robot -d results tests/
    displayName: 'Run Tests'
